version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8000:8080"
    depends_on:
      - api
    volumes:
      -  "./openapi.yaml:/openapi.yaml"
    environment:
      SWAGGER_JSON: /openapi.yaml

  api:
    tty: true
    build: .
    volumes:
      - "./api:/usr/api"
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'

volumes:
  db-data:
    driver: local
