CREATE SCHEMA IF NOT EXISTS `swagger_sample` DEFAULT CHARACTER SET utf8mb4 ;
USE `swagger_sample` ;

SET CHARSET utf8mb4 ;

CREATE TABLE IF NOT EXISTS `swagger_sample`.`todos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `subject`     TEXT     NOT NULL,
  `description` TEXT     NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
